config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/tasks', to: 'tasks#index'

  # #new
  # get '/tasks/new', to: 'tasks#new'
  # post 'tasks/', to: 'tasks#create'

  # #show
  # get '/tasks/:id', to: 'tasks#show', as: :task

  # #edit
  # get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # patch '/tasks/:id', to: 'tasks#update'

  # #destroy
  # delete 'tasks/:id', to: 'tasks#destroy'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    # not using a variable in a view so no need to use @ symbol
    # using the (filtered) strong params to create the new restaurant
    task = Task.create(task_params)
    # redirecting to the show view of the restaurant
    redirect_to task_path(task)
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

private

  def task_params
    return params.require(:task).permit(:title, :details, :completed)
  end
end


# As a user, I can list tasks
# As a user, I can view the details of a task
# As a user, I can add a new task
# As a user, I can edit a task (mark as completed / update title & details)
# As a user, I can remove a task

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'shared/form' %>

app/views/tasks/index.html.erb
<div class='main-ccontainer'>

  <h3>My Tasks</h3>

  <ul>
    <% @tasks.each do |task| %>
    <% if task.completed %>
        <li><input id="checkBox" type="checkbox" checked>
      <% else %>
        <li><input id="checkBox" type="checkbox">
      <% end %>
      <%= link_to task.title, task_path(task) %>
      - <%= link_to 'Delete', task_path(task), method: :delete  %>
      - <%= link_to 'Edit', edit_task_path(task) %>
    </li>
    <% end %>
  </ul>

<%= link_to 'Create a new task', new_task_path %>

</div>

app/views/tasks/new.html.erb
<%= render 'shared/form' %>

app/views/tasks/show.html.erb
<div class='main-ccontainer'>

  <h3><%= @task.title %></h3>

  <div>
    <%= @task.details %>
  </div>
  <br>
  <div>
    <%= link_to 'Go to overview', tasks_path %>
  </div>
</div>